---
- name: Install nginx
  hosts: lighthouse
  handlers:
    - name: Start-nginx
      become: true
      ansible.builtin.command: nginx
      register: nginx_output
      changed_when: nginx_output.rc != 0
    - name: Reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
      register: nginx_output
      changed_when: nginx_output.rc = 0
  tasks:
    - name: NGINX | Install NGINX
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: Start-nginx
    - name: NGINX | Create general config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0744'
      notify: Reload-nginx

- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: Reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
      register: nginx_output
      changed_when: nginx_output.rc == 0
  pre_tasks:
    - name: Lighthouse | install dependencies
      become: true
      ansible.builtin.package:
        name: git
        state: present
        update_cache: true
  tasks:
    - name: Lighthouse | Copy from git
      ansible.builtin.git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir }}"
    - name: Lighthouse | Create lighthouse config
      become: true
      ansible.builtin.template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: '0744'
      notify: Reload-nginx

- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
    - name: Restart vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: restarted
        daemon_reload: true
  tasks:
    - name: Clickhouse
      become: true
      block:
        - name: Install gpg
          ansible.builtin.package:
            name: gpg
            state: present
            update_cache: true
        - name: Install by APT | Apt-key add repo key
          ansible.builtin.apt_key:
            keyserver: "{{ clickhouse_repo_keyserver }}"
            id: "{{ clickhouse_repo_key }}"
        - name: Install by APT | Remove old repo
          ansible.builtin.apt_repository:
            repo: "{{ clickhouse_repo_old }}"
            state: absent
          when: clickhouse_repo_old is defined
        - name: Install by APT | Repo installation
          ansible.builtin.apt_repository:
            repo: "{{ clickhouse_repo }}"
            state: present
        - name: Install clickhouse packages
          ansible.builtin.apt:
            name:
              - clickhouse-common-static
              - clickhouse-client
              - clickhouse-server
          notify: Start clickhouse service
        - name: Flush handlers
          ansible.builtin.meta: flush_handlers
        - name: Create database
          ansible.builtin.command: "clickhouse-client -q 'create database sample;'"
          register: create_db
          failed_when: 'create_db.rc != 0 and create_db.rc != 82'
          changed_when: create_db.rc == 0

- name: Vector
  hosts: vector
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: restarted
        daemon_reload: true
  tasks:
    - name: Install vector
      become: true
      block:
        - name: Install Vector | prepare architecture name when x64
          ansible.builtin.set_fact:
            architecture_name: amd64
          when: ansible_architecture == 'x86_64'
        - name: Install Vector | prepare architecture name when else
          ansible.builtin.set_fact:
            architecture_name: undefined
          when: ansible_architecture != 'x86_64'
        - name: Install Vector | DEB install
          become: true
          ansible.builtin.apt:
            deb: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_{{ architecture_name }}.deb
            state: present
          notify: Restart vector service

    - name: Configure vector
      become: true
      block:
        - name: Configure Vector | ensure what directory exists
          ansible.builtin.file:
            path: "{{ vector_config_dir }}"
            state: directory
            mode: '0744'
        - name: Configure Vector | Template config
          ansible.builtin.template:
            src: vector.yml.j2
            mode: '0744'
            dest: "{{ vector_config_dir }}/vector.yml"
          notify: Restart vector service
        - name: Configure Service | Template systemd unit
          ansible.builtin.template:
            src: vector.service.j2
            dest: /etc/systemd/system/vector.service
            mode: '0744'
          notify: Restart vector service
