---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  ansible-lint .
  yamlint .
platforms:
  - name: centos_7
    image: pycontribs/centos:7
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - destroy
    - create
    - converge
    - destroy